use_frameworks!

platform :ios, '8.0'

target 'libamzi_Example' do
  pod 'libamzi', :path => '../'

  target 'libamzi_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
